- hosts: localhost
  vars:
    projects: "{{ lookup('env', 'HOME') }}/projects"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  - name: Installing stow
    apt: name=stow
    tags:
      - install
      - dotfiles
      - stow
  - name: Cloning dotfiles
    ansible.builtin.git:
        repo: 'git@github.com:alif-mohdamir/dotfiles.git'
        dest: "{{ lookup('env', 'HOME') }}/projects/dotfiles"
        recursive: yes
        update: yes
        accept_hostkey: yes
        version: master
    tags:
      - install
      - dotfiles
      - stow
  - name: Stow dotfiles
    shell: cd $HOME/projects/dotfiles $$ ./install.sh
    tags:
      - install
      - dotfiles
      - stow
