#!/bin/sh
# Regenerates prose-rules.md (the subagent-facing copy) from the Plain Prose output style.
# The style file is the source of truth; edit it, then run this.
set -eu
cd "$(dirname "$0")"

SRC=output-styles/plain-prose.md
OUT=prose-rules.md

# Line 11 is the "## Banned constructions" heading. Everything above it is frontmatter plus
# the "you are an interactive CLI tool" preamble, which must not reach a subagent: it would
# tell the subagent it is the top-level agent talking to a human.
START=$(grep -n '^## Banned constructions' "$SRC" | cut -d: -f1)

{
  echo "<!-- GENERATED by regen-prose-rules.sh from $SRC. Do not edit this file. -->"
  echo
  echo "# Prose rules"
  echo
  echo "These govern everything you write: chat replies, code comments, commit messages, PR"
  echo "descriptions, changelog entries, docs, and any text you return to a calling agent."
  echo
  tail -n "+$START" "$SRC"
} > "$OUT"

echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines) from $SRC line $START onward"
